version: '2'

services:
  sensu:
    build: ./sensu
    volumes:
      - "./config/sensu.json:/etc/sensu/config.json:ro"
      - "./config/sensu-checks.json:/etc/sensu/conf.d/checks.json:ro"
      - "./ssl/server/cert.pem:/etc/sensu/ssl/cert.pem:ro"
      - "./ssl/server/key.pem:/etc/sensu/ssl/key.pem:ro"
    depends_on:
      - rabbitmq
      - redis

  uchiwa:
    image: uchiwa/uchiwa
    ports:
      - "3000:3000"
    volumes:
      - "./config/uchiwa.json:/config/config.json:ro"
    depends_on:
      - sensu

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # Optional, only opened for rabbitmq management
      - "5671:5671" # Opened for Sensu clients
    volumes:
      - "./config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      - "./ssl/sensu_ca/cacert.pem:/etc/rabbitmq/ssl/cacert.pem:ro"
      - "./ssl/server/cert.pem:/etc/rabbitmq/ssl/cert.pem:ro"
      - "./ssl/server/key.pem:/etc/rabbitmq/ssl/key.pem:ro"
